### ISSUE TITLE
Angular: controllerAs syntax doesn't work.

### ISSUE THREAD

**Issue by icholy** [icholy/uzi#12]
Variables referencing rects should be prefixed with `#` or `~` and all other variable lookups can be directed somewhere else (to angular's `$parse` for example).

**Comment by icholy** [comment]
Another option is to incorporate namespaces. So everything in the angular context would be in the `ng` context. Example:

``` scss
#A {
   width: B.width / 2;
   height: ng.$ctrl.someVariable + 100px;
}
```
